var captions = {
  before: [
    "BUT IT'S NEVER TOO EARLY TO PREGAME",
    "BUT IT'S NEVER TOO EARLY TO PREGAME",
    "BUT I CAN'T BELIEVE PEOPLE READ THIS SHIT",
    "BUT IT MAKES CMU WORTH IT",
    "BUT BOOTH BOOTH BOOTH BOOTH BOOTH",
    "BUT HOLY FUCK IT NEEDS TO BE",
    "BUT IT'S NOT LIKE YOU'LL REMEMBER IT ANYWAY",
    "BUT IT'S NOT LIKE YOU'LL REMEMBER IT ANYWAY",
    "BUT WHERE THE FUCK IS MIDWAY",
    "BUT WHERE THE FUCK IS MIDWAY",
    "BUT PRAY IT DOESNT SNOW",
    "BUT PRAY IT DOESNT RAIN",
    "BUT WHY IS IT SO EARLY",
    "BUT IT'S LIT",
    "BUT IT'S LIT",
    "BUT START PREPARING YOUR LIVER",
  ]
}
